# Drupal with MySQL
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
version: '3.2'

services:

  drupal:
    image: drupal:10-apache
    container_name: drupal10_app

    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./web/modules/custom
        target: /var/www/html/modules/custom
      - type: bind
        source: ./web/sites/default/settings.php
        target: /var/www/html/sites/default/settings.php
    restart: always

  mysql:
    image: mysql:8
    container_name: drupal10_mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - type: bind
        source: ./database
        target: /docker-entrypoint-initdb.d
    restart: always