# Drupal with MySQL
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
version: '3.2'

services:

  drupal:
    container_name: drupal10_app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - "2222:22"
    volumes:
      # bind custom modules
      - type: bind
        source: ./web/modules/custom
        target: /var/www/html/modules/custom
      # bind cutom themes
      - type: bind
        source: ./web/themes/custom
        target: /var/www/html/themes/custom
      # bind settings.php
      - type: bind
        source: ./web/sites/default/settings.php
        target: /var/www/html/sites/default/settings.php
      # bind files
      - type: bind
        source: ./web/sites/default/files
        target: /var/www/html/sites/default/files
    restart: always

  mysql:
    image: mysql:8
    container_name: drupal10_mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      # This bind allows to import the local database into the continer
      - type: bind
        source: ./database
        target: /docker-entrypoint-initdb.d
    restart: always
